### ISSUE TITLE
get verificarlo dockerhub access

### ISSUE THREAD

**Issue by gkiar** [verificarlo/fuzzy#27]
@pablooliveira could you please give either @yohanchatelain or I access to the verificarlo Dockerhub org so we can setup Github actions on this project to publish images as `verificarlo/fuzzy:tag`? If you don't want to do this, you could alternatively add the two following secrets to this project using your credentials: 

```
DOCKER_HUB_USERNAME
DOCKER_HUB_ACCESS_TOKEN
```

Thanks!

**Comment by pablooliveira** [comment]
@gkiar I have given you administrative access to verificarlo `hub.docker.com` organisation so you should be able to set up verificarlo/fuzzy. 

Thanks !

**Comment by pablooliveira** [comment]
(Unfortunately the number of admin access is pretty limited on the free plan, so I have only given one of you access to save one slot for future needs, I hope that is ok)

**Comment by gkiar** [comment]
Thanks, @pablooliveira ! It seems that since migrating this to verificarlo org on github I don't have admin access on the repo anymore, so I can't add the secret key; would you be able to also add me as an admin on the repo? Thanks so much!

**Comment by pablooliveira** [comment]
You should be administrator again.
